version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onfly-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: onfly-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_DATABASE: onfly_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
